export const appRoutes = {
  home: "/",
  login: "/login",
  register: "/register",
  userDashboard: "/dashboard",
  userInterview: "/interview/setup",
  userInterviewSetup: "/interview/setup",
  userInterviewSession: (sessionId: string | number) =>
    `/interview/sessions/${sessionId}`,
  userInterviews: "/interviews",
  userPractice: "/practice",
  mockTests: "/mock-tests",
  mockTestDetail: (id: number | string) => `/mock-tests/${id}`,
  mockTestAttempt: (attemptId: number | string) =>
    `/mock-tests/attempts/${attemptId}`,
  mockTestResult: (attemptId: number | string) =>
    `/mock-tests/attempts/${attemptId}/result`,
  userJobs: "/jobs",
  userResumes: "/resumes",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminQuestionBanks: "/admin/question-banks",
  adminInterviewTechnologies: "/admin/interview-technologies",
  adminInterviewTopics: "/admin/interview-topics",
  adminInterviewLevels: "/admin/interview-levels",
  adminInterviewPositions: "/admin/interview-positions",
  adminMockTests: "/admin/mock-tests",
  adminJobs: "/admin/jobs",
  adminUsers: "/admin/users",
};
